#!/usr/bin/nft -f
flush ruleset

table inet tinyhat {
	set tcp_open {
		type inet_service
	}

	set udp_open {
		type inet_service
	}

	chain input {
		type filter hook input priority filter; policy drop;
		ct state established,related accept
		ct state invalid drop
		iif lo accept
		meta l4proto { icmp, ipv6-icmp } limit rate 20/second accept
		udp dport { 68, 546 } accept
		tcp dport @tcp_open accept
		udp dport @udp_open accept
		meta l4proto tcp reject with tcp reset
		reject
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
	}
}
