vm.swappiness = 150
vm.page-cluster = 0
vm.watermark_scale_factor = 125
kernel.sysrq = 1
vm.dirty_expire_centisecs = 300
vm.dirty_writeback_centisecs = 100
vm.compaction_proactiveness = 0
vm.watermark_boost_factor = 1
vm.zone_reclaim_mode = 0
vm.page_lock_unfairness = 1
