[sdl]
fullscreen=false
output=surface
fullresolution=original
autolock=false

[dosbox]
quit warning=false
memsize=16
startbanner=false

[render]
aspect=false
modeswitch=true
frameskip=2

[cpu]
core=auto
cputype=auto
cycles=auto

[mixer]
rate=44100
blocksize=2048
prebuffer=100

[midi]
mpu401=intelligent
mididevice=fluidsynth
fluid.driver=pipewire
fluid.soundfont=/usr/share/soundfonts/GeneralUser-GS-2.0.3.sf3
fluid.samplerate=44100
fluid.chorus=no
fluid.reverb=no
fluid.polyphony=64
fluid.periods=4
fluid.periodsize=1024
